*&---------------------------------------------------------------------*
*& Report Y_EVENTS
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT y_events.

DATA lv_date TYPE yde_invdate.


SELECTION-SCREEN: BEGIN OF BLOCK b1 WITH FRAME TITLE TEXT-000.
PARAMETERS : inv_no   TYPE yde_invno OBLIGATORY,
             inv_type TYPE yde_invtype.

SELECT-OPTIONS : inv_date FOR lv_date .

SELECTION-SCREEN: BEGIN OF BLOCK b2 WITH FRAME TITLE TEXT-001.
SELECTION-SCREEN: BEGIN OF LINE.

PARAMETERS : p_r1 TYPE c RADIOBUTTON GROUP r1.
SELECTION-SCREEN: COMMENT 3(3) TEXT-002.
PARAMETERS :p_r2 TYPE c RADIOBUTTON GROUP r1.
SELECTION-SCREEN: COMMENT 9(7) TEXT-003.
PARAMETERS :p_r3 TYPE c RADIOBUTTON GROUP r1.
SELECTION-SCREEN: COMMENT 19(8) TEXT-004.
SELECTION-SCREEN: END OF LINE.
SELECTION-SCREEN : END OF BLOCK b2.

SELECTION-SCREEN : BEGIN OF LINE.
PARAMETERS : p_chk1 AS CHECKBOX.
SELECTION-SCREEN: COMMENT 3(8) TEXT-005.
PARAMETERS : p_chk2 AS CHECKBOX.
SELECTION-SCREEN: COMMENT 14(8) TEXT-006.
SELECTION-SCREEN : END OF LINE.
SELECTION-SCREEN : END OF BLOCK b1.
